"""Reproduces two live contract breaks around the engine `info` dict.

DEFECT 1 (silent, browser only)
    engine removed `info["landing_height"]` (ownership moved to
    rl/features.py, docs/spec.md 317). `web/policies.js` still reads it as
    `info.landing_height || 0`, so feature 0 -- the one carrying the largest
    Dellacherie weight, -4.500158825082766 -- is CONSTANT ZERO in the browser.
    Nothing throws. The ARENA panels just play worse than the numbers rl
    reports from Python, and no test anywhere notices.

DEFECT 2 (loud, latent)
    `rl/features.py:extract_from_info` does `float(info["landing_height"])`,
    which is now a KeyError on every call.

DEFECT 3 (doc/impl contradiction)
    `docs/spec.md` still states "콤보·B2B 보너스 없음" and PROJECT.md fixes the
    score table at single/double/triple/tetris = 100/300/500/800 x level, but
    the engine now applies a x1.5 back-to-back multiplier and a
    COMBO_BONUS_PER_STEP combo bonus. The score the user sees no longer
    matches either document.

Run:  python3 tests/test_info_contract.py
Owners: engine (info contract, spec.md), web (policies.js).
This file is checker-owned.
"""

import json
import os
import shutil
import subprocess
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
sys.path.insert(0, os.path.join(_ROOT, "engine"))

import engine as E  # noqa: E402

WEB = os.path.join(_ROOT, "web")
JS_RUNNER = os.path.join(_HERE, "_info_runner.mjs")

FAILURES = []


def fail(tag, msg):
    FAILURES.append((tag, msg))
    print("  FAIL [%s] %s" % (tag, msg))


def ok(msg):
    print("  ok   %s" % msg)


JS_SRC = r"""// generated by tests/test_info_contract.py -- checker owned
import * as E from '%(web)s/engine.js';
import * as P from '%(web)s/policies.js';

// Play a game with the engine's own placement order and record, per lock,
// what policies.js believes feature 0 (landing_height) is, next to the value
// that is actually reconstructible from info.piece_cells.
let s = E.newGame(20260807);
const rows_out = [];
for (let i = 0; i < 400; i++) {
  const ps = E.legalPlacements(s);
  if (ps.length === 0) break;
  // deepest landing, ties to the earlier placement
  let b = 0, by = ps[0][2];
  for (let k = 1; k < ps.length; k++) if (ps[k][2] > by) { by = ps[k][2]; b = k; }
  const [ns, info] = E.applyPlacement(s, ps[b]);
  s = ns;
  const f = P.features(s.rows, info);
  // truth: mean height above the floor of the four locked cells, floor = 1
  let sum = 0;
  for (const [y] of info.piece_cells) sum += (E.ROWS - y);
  rows_out.push({
    feat0_from_policies: f[0],
    truth_landing_height: sum / 4,
    feat1_from_policies: f[1],
    truth_eroded: info.eroded_piece_cells,
    has_landing_height: Object.prototype.hasOwnProperty.call(info, 'landing_height'),
    score_delta: info.score_delta,
    lines_cleared: info.lines_cleared,
    b2b_active: info.b2b_active,
    combo_count: info.combo_count,
    level: info.level,
  });
  if (s.game_over) break;
}
process.stdout.write(JSON.stringify(rows_out));
"""


def defect_1_and_2():
    print("\n1+2. info['landing_height'] removed; consumers not updated")

    s = E.new_game(20260807)
    ps = E.legal_placements(s)
    _ns, info = E.apply_placement(s, ps[0])
    if "landing_height" in info:
        ok("engine still provides landing_height -- defects 1 and 2 are fixed")
        return
    print("    engine info keys now: %s" % sorted(info.keys()))
    ok("confirmed: engine no longer emits 'landing_height' (by design, "
       "docs/spec.md 317 -- ownership moved to rl/features.py)")

    # DEFECT 2: rl/features.py wrapper
    sys.path.insert(0, os.path.join(_ROOT, "rl"))
    try:
        import numpy as np
        import features as F
        board = np.zeros((E.VISIBLE_ROWS, E.W), dtype=np.int8)
        try:
            F.extract_from_info(board, info)
            ok("rl/features.py extract_from_info still works")
        except KeyError as e:
            fail("D2", "rl/features.py:extract_from_info raises KeyError(%s) "
                       "on the current engine info dict -- it reads "
                       "info['landing_height'], which no longer exists" % e)
    except ImportError as e:
        print("    (skipped rl check: %s)" % e)

    # DEFECT 1: web/policies.js
    node = shutil.which("node")
    if not node:
        fail("D1", "node unavailable -- cannot check web/policies.js")
        return
    with open(JS_RUNNER, "w") as f:
        f.write(JS_SRC % {"web": WEB.replace("\\", "/")})
    proc = subprocess.run([node, JS_RUNNER], capture_output=True, text=True)
    if proc.returncode != 0:
        fail("D1", "node runner failed (web/engine.js or policies.js will not "
                   "load):\n" + proc.stderr[-1500:])
        return
    recs = json.loads(proc.stdout)
    if not recs:
        fail("D1", "JS runner produced no locks")
        return
    zero = sum(1 for r in recs if r["feat0_from_policies"] == 0)
    truth_nonzero = sum(1 for r in recs if r["truth_landing_height"] != 0)
    if zero == len(recs) and truth_nonzero:
        ex = next(r for r in recs if r["truth_landing_height"] != 0)
        fail("D1", "web/policies.js features()[0] is 0 on ALL %d locks while "
                   "the true landing_height is non-zero on %d of them "
                   "(e.g. %.2f). policies.js reads `info.landing_height || 0`; "
                   "the field is gone, so the feature with the largest "
                   "Dellacherie weight (-4.500158825082766) is constant 0 in "
                   "the browser and nothing throws."
             % (len(recs), truth_nonzero, ex["truth_landing_height"]))
    elif zero == 0:
        ok("web/policies.js feature 0 is populated (%d locks)" % len(recs))
    else:
        print("    feature 0 was zero on %d of %d locks" % (zero, len(recs)))
    # feature 1 should still be fine -- prove the harness is not broken
    bad1 = sum(1 for r in recs
               if r["feat1_from_policies"] != r["truth_eroded"])
    if bad1:
        fail("D1", "feature 1 (eroded_piece_cells) also wrong on %d locks"
             % bad1)
    else:
        ok("control: feature 1 (eroded_piece_cells) matches info exactly on "
           "all %d locks, so the harness itself is sound -- only feature 0 "
           "is dead" % len(recs))
    return recs


def defect_3(recs):
    print("\n3. score contract: spec.md/PROJECT.md say no combo/B2B bonus")
    spec = os.path.join(_ROOT, "docs", "spec.md")
    txt = open(spec, encoding="utf-8").read()
    says_none = "콤보·B2B 보너스 없음" in txt
    engine_has = all(hasattr(E, n) for n in
                     ("B2B_LINES", "B2B_MULT_NUM", "COMBO_BONUS_PER_STEP")) \
        or True
    from tables import (B2B_LINES, B2B_MULT_DEN, B2B_MULT_NUM,  # noqa: E402
                        COMBO_BONUS_PER_STEP, SCORE_TABLE)
    print("    tables.py: B2B_LINES=%d, multiplier=%d/%d, "
          "COMBO_BONUS_PER_STEP=%d"
          % (B2B_LINES, B2B_MULT_NUM, B2B_MULT_DEN, COMBO_BONUS_PER_STEP))
    if says_none:
        fail("D3", "docs/spec.md still says \"콤보·B2B 보너스 없음\" but the "
                   "engine applies a x%d/%d back-to-back multiplier and a "
                   "%d-per-step combo bonus. One of the two is wrong."
             % (B2B_MULT_NUM, B2B_MULT_DEN, COMBO_BONUS_PER_STEP))
    else:
        ok("docs/spec.md documents the combo/B2B rules")

    # PROJECT.md is the lead's document; it must carry the same rule. It now
    # states a checksum sentence, so verify THAT against the engine rather
    # than against a number hardcoded here.
    proj = os.path.join(_ROOT, "PROJECT.md")
    ptxt = open(proj, encoding="utf-8").read()
    b2b, combo, total = 0, 0, 0
    for _ in range(2):
        d, b2b, combo, _a = tuple(E._score_clear(4, 1, b2b, combo))[:4]
        total += d
    if str(total) in ptxt:
        ok("PROJECT.md carries a checksum for two back-to-back tetrises at "
           "level 1 and it matches the engine exactly (%d)" % total)
        return
    if "콤보" not in ptxt and "B2B" not in ptxt:
        fail("D3", "PROJECT.md's score section does not mention combo/B2B at "
                   "all, but the engine applies both. Two back-to-back "
                   "tetrises at level 1 score %d in the engine." % total)
    else:
        fail("D3", "PROJECT.md describes combo/B2B but carries no checksum "
                   "matching the engine's %d for two back-to-back tetrises at "
                   "level 1. Add the number so a future drift is caught."
             % total)

    if recs:
        seen_b2b = sum(1 for r in recs if r.get("b2b_active"))
        seen_combo = sum(1 for r in recs if (r.get("combo_count") or 0) > 1)
        print("    in the 400-move JS game: b2b_active on %d locks, "
              "combo_count>1 on %d locks" % (seen_b2b, seen_combo))


def main():
    print("=" * 74)
    print("checker: engine `info` contract breaks")
    print("=" * 74)
    recs = defect_1_and_2()
    defect_3(recs or [])
    print("\n" + "=" * 74)
    if FAILURES:
        print("RESULT: %d DEFECT(S) REPRODUCED" % len(FAILURES))
        for tag, msg in FAILURES:
            print("  [%s] %s" % (tag, msg.splitlines()[0]))
        return 1
    print("RESULT: no contract break found.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
