"""Independent third implementation of the two `wells10` features.

rl added `max_well_depth` and `well_count`, and asked for the same treatment I
gave the original eight: a THIRD implementation written from the prose
definitions alone, so that agreement is not two-of-rl's-own-code agreeing with
itself. rl's own cross-check (numpy reference vs bitboard, 3,000 boards, zero
mismatches) is real but both sides are rl's.

So the loops below are written from `weights/wells10_reference.json`'s
`definition` block ONLY -- not from `rl/features.py`, and not from rl's message.
Plain Python, no numpy, no bitmasks, deliberately the dumbest possible reading
of the prose:

    well cell : empty, and BOTH horizontal neighbours filled. Walls (column -1
                and column 10) count as filled. Identical predicate to
                cumulative_wells -- only the aggregation differs.
    run       : a vertically CONTIGUOUS group of well cells. A filled cell in
                the middle splits it into separate runs.
    max_well_depth : size of the largest run, 0 if there are none.
    well_count     : number of runs of size >= 3. Below the threshold: not
                     counted.
    board     : the visible 20 rows only.

Three comparisons, because each catches something different:
  1. my loops vs rl's 8 HAND-COMPUTED fixtures -- catches a misread of the
     prose. rl flagged `split_well` as the easiest to get wrong (runs are
     contiguous groups, not per-column totals), so that one is decisive.
  2. my loops vs rl's 300 random-board expectations -- catches a rule that
     happens to work on small hand cases.
  3. my loops vs the LIVE rl/features.py -- catches the reference file having
     been generated by code that has since changed.

Also asserted: the wells10 predicate really is the same as cumulative_wells's,
since rl says so in writing and that claim is load-bearing (if they drifted, a
board could have wells by one definition and not the other).

Run:  <ml python> tests/test_wells10_features.py
Owner of the code under test: rl.  This file is checker-owned.
"""

import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
sys.path.insert(0, os.path.join(_ROOT, "rl"))

REF = os.path.join(_ROOT, "weights", "wells10_reference.json")

PASSED, FAILED, SKIPPED = [], [], []


def ok(m):
    PASSED.append(m)
    print("  ok   %s" % m)


def fail(t, m):
    FAILED.append((t, m))
    print("  FAIL [%s] %s" % (t, m))


def skip(t, m):
    SKIPPED.append((t, m))
    print("  SKIP [%s] %s" % (t, m))


# ===========================================================================
# my implementation -- from the prose only
# ===========================================================================

def well_cells(board):
    """Set of (r, c) that are well cells. Walls count as filled."""
    rows = len(board)
    cols = len(board[0]) if rows else 0
    out = set()
    for r in range(rows):
        for c in range(cols):
            if board[r][c]:
                continue                      # must be EMPTY
            left = 1 if c == 0 else board[r][c - 1]      # wall = filled
            right = 1 if c == cols - 1 else board[r][c + 1]
            if left and right:
                out.add((r, c))
    return out


def well_runs(board):
    """Lengths of vertically contiguous runs of well cells.

    Walk each column top to bottom. A well cell extends the current run; ANY
    non-well cell (filled, or empty-but-not-a-well) ends it. That is what
    "a filled cell in the middle splits it into separate runs" means, read
    literally -- the run is a maximal contiguous group, not a per-column total.
    """
    cells = well_cells(board)
    rows = len(board)
    cols = len(board[0]) if rows else 0
    lengths = []
    for c in range(cols):
        run = 0
        for r in range(rows):
            if (r, c) in cells:
                run += 1
            else:
                if run:
                    lengths.append(run)
                run = 0
        if run:
            lengths.append(run)
    return lengths


def my_max_well_depth(board):
    runs = well_runs(board)
    return max(runs) if runs else 0


def my_well_count(board, threshold=3):
    return sum(1 for n in well_runs(board) if n >= threshold)


def my_cumulative_wells(board):
    """cumulative_wells, re-derived here purely so the shared-predicate claim
    can be checked: a well of depth d contributes 1+2+...+d."""
    cells = well_cells(board)
    rows = len(board)
    cols = len(board[0]) if rows else 0
    total = 0
    for c in range(cols):
        depth = 0
        for r in range(rows):
            if (r, c) in cells:
                depth += 1
                total += depth
            else:
                depth = 0
    return total


# ===========================================================================

def main():
    print("=" * 74)
    print("checker: third independent implementation of the wells10 features")
    print("=" * 74)
    if not os.path.exists(REF):
        skip("W0", "weights/wells10_reference.json absent -- the two new "
                   "features are UNVERIFIED by me")
        return report()
    ref = json.load(open(REF, encoding="utf-8"))
    print("\n0. reference file")
    print("      board_format : %s" % ref.get("board_format"))
    print("      feature_order: %s" % ", ".join(ref.get("feature_order", [])))
    print("      fixtures     : %d hand-computed, %d random"
          % (len(ref.get("hand_fixtures", [])),
             len(ref.get("random_boards", []))))
    d = ref.get("definition") or {}
    for k in ("well_cell", "run", "max_well_depth", "well_count"):
        if k in d:
            print("      %-15s %s" % (k + ":", d[k]))

    # ---- 1. hand-computed fixtures
    print("\n1. my loops vs rl's %d HAND-COMPUTED fixtures"
          % len(ref.get("hand_fixtures", [])))
    bad = 0
    for fx in ref.get("hand_fixtures", []):
        name, board = fx["name"], fx["board"]
        exp = fx["expected"]
        got = {"max_well_depth": my_max_well_depth(board),
               "well_count": my_well_count(board)}
        marks = []
        for k in ("max_well_depth", "well_count"):
            if k in exp:
                agree = exp[k] == got[k]
                marks.append("%s exp=%s mine=%s %s"
                             % (k, exp[k], got[k], "ok" if agree else "MISMATCH"))
                if not agree:
                    bad += 1
        print("      %-20s %s" % (name, " | ".join(marks)))
        if any("MISMATCH" in m for m in marks):
            fail("W1", "fixture %r: my reading of the prose disagrees with rl's "
                       "hand computation (%s). Board rows: %r"
                 % (name, " ; ".join(marks), board))
    if bad == 0:
        names = [f["name"] for f in ref.get("hand_fixtures", [])]
        ok("all %d hand fixtures agree, including the ones rl flagged as "
           "boundary cases: %s. `split_well` is the decisive one -- it confirms "
           "runs are CONTIGUOUS groups, not per-column totals (a per-column "
           "reading would give 4 and 1 there instead of 2 and 0)."
           % (len(names), ", ".join(names)))

    # ---- 2. random boards
    rb = ref.get("random_boards", [])
    print("\n2. my loops vs rl's %d random-board expectations" % len(rb))
    mm = {"max_well_depth": 0, "well_count": 0}
    first = None
    for i, item in enumerate(rb):
        board, exp = item["board"], item["expected"]
        got = {"max_well_depth": my_max_well_depth(board),
               "well_count": my_well_count(board)}
        for k in mm:
            if k in exp and exp[k] != got[k]:
                mm[k] += 1
                if first is None:
                    first = (i, k, exp[k], got[k], board)
    if sum(mm.values()) == 0:
        ok("%d random boards: %s agree exactly with rl's expectations"
           % (len(rb), " and ".join(sorted(mm))))
    else:
        i, k, e, g, board = first
        fail("W2", "%r on %d random boards (first at index %d: %s expected %s, "
                   "mine %s). Board: %r"
             % (mm, len(rb), i, k, e, g, board))

    # ---- 3. the LIVE rl/features.py, not just the frozen file
    print("\n3. my loops vs the LIVE rl/features.py")
    try:
        import numpy as np
        import features as F
    except ImportError as e:
        skip("W3", "cannot import rl/features.py or numpy (%s) -- the frozen "
                   "reference file was checked but the LIVE code was not" % e)
    else:
        fns = {}
        for nm in ("max_well_depth", "well_count"):
            fn = getattr(F, nm, None)
            if callable(fn):
                fns[nm] = fn
        if not fns:
            skip("W3", "rl/features.py exposes neither max_well_depth nor "
                       "well_count as a function -- could not compare against "
                       "the live code (only the frozen reference file)")
        else:
            print("      found in features.py: %s" % ", ".join(sorted(fns)))
            bad2 = {k: 0 for k in fns}
            firstbad = None
            boards = ([f["board"] for f in ref.get("hand_fixtures", [])]
                      + [b["board"] for b in rb])
            for board in boards:
                arr = np.array(board, dtype=np.int8)
                mine = {"max_well_depth": my_max_well_depth(board),
                        "well_count": my_well_count(board)}
                for nm, fn in fns.items():
                    live = int(fn(arr))
                    if live != mine[nm]:
                        bad2[nm] += 1
                        if firstbad is None:
                            firstbad = (nm, live, mine[nm], board)
            if sum(bad2.values()) == 0:
                ok("%d boards: the live rl/features.py agrees with my "
                   "independent loops on %s -- so the reference file was not "
                   "generated by code that has since drifted"
                   % (len(boards), ", ".join(sorted(fns))))
            else:
                nm, live, mine_v, board = firstbad
                fail("W3", "the LIVE rl/features.py disagrees with my loops: %r "
                           "(first: %s live=%s mine=%s). The frozen reference "
                           "file may have been generated by an older version."
                     % (bad2, nm, live, mine_v))

    # ---- 4. the shared-predicate claim, which is load-bearing
    print("\n4. rl's claim: the well-cell predicate is IDENTICAL to "
          "cumulative_wells's")
    boards = ([f["board"] for f in ref.get("hand_fixtures", [])]
              + [b["board"] for b in rb])
    bad3 = 0
    for item, board in zip(list(ref.get("hand_fixtures", [])) + list(rb),
                           boards):
        exp = item.get("expected", {})
        if "cumulative_wells" not in exp:
            continue
        if my_cumulative_wells(board) != exp["cumulative_wells"]:
            bad3 += 1
    n_cw = sum(1 for it in list(ref.get("hand_fixtures", [])) + list(rb)
               if "cumulative_wells" in it.get("expected", {}))
    if n_cw == 0:
        skip("W4", "the reference carries no cumulative_wells expectations, so "
                   "the shared-predicate claim was NOT cross-checked")
    elif bad3 == 0:
        ok("%d boards: cumulative_wells recomputed from the SAME well-cell "
           "predicate I used for the wells10 features matches rl's "
           "expectations, so the two features really do share one predicate "
           "and differ only in aggregation -- the claim holds, and a board "
           "cannot have wells under one definition and not the other" % n_cw)
    else:
        fail("W4", "cumulative_wells disagrees on %d of %d boards when computed "
                   "from the well-cell predicate I used for wells10. Then the "
                   "two features do NOT share a predicate, and rl's written "
                   "claim that they differ only in aggregation is wrong."
             % (bad3, n_cw))

    # ---- 5. threshold sensitivity, so the '3' is pinned
    print("\n5. is the well_count threshold really 3?")
    alt = {2: 0, 3: 0, 4: 0}
    for item, board in zip(list(ref.get("hand_fixtures", [])) + list(rb),
                           boards):
        exp = item.get("expected", {})
        if "well_count" not in exp:
            continue
        for t in alt:
            if my_well_count(board, t) == exp["well_count"]:
                alt[t] += 1
    total = sum(1 for it in list(ref.get("hand_fixtures", [])) + list(rb)
                if "well_count" in it.get("expected", {}))
    print("      boards matching rl's well_count with threshold 2/3/4: "
          "%d / %d / %d  (of %d)" % (alt[2], alt[3], alt[4], total))
    if total and alt[3] == total and alt[2] < total and alt[4] < total:
        ok("threshold 3 matches every board while 2 and 4 do not, so the "
           "documented '>= 3' is pinned by the data and not merely asserted")
    elif total and alt[3] == total:
        ok("threshold 3 matches every board (2 and 4 also matched %d/%d and "
           "%d/%d, so this data does not fully discriminate the threshold)"
           % (alt[2], total, alt[4], total))
    check_feature_set_contract(ref)
    return report()


def check_feature_set_contract(ref):
    """Three claims rl made in writing, each load-bearing.

    Verified here rather than taken on trust because each one, if wrong, fails
    SILENTLY: a zero-filled unknown feature looks like a weak policy, and a
    changed 8-feature path looks like a regression somewhere else entirely.
    """
    print("\n6. the FEATURE_SETS contract")
    try:
        import numpy as np
        import features as F
    except ImportError as e:
        skip("W6", "cannot import rl/features.py or numpy (%s) -- the "
                   "FEATURE_SETS contract was NOT checked" % e)
        return
    sets = getattr(F, "FEATURE_SETS", None)
    if not sets:
        skip("W6", "rl/features.py has no FEATURE_SETS -- contract not checked")
        return
    print("      FEATURE_SETS: %s"
          % {k: len(v) for k, v in sorted(sets.items())})

    # (a) the 10-feature set must EXTEND the 8, not reorder it. A consumer that
    #     builds vectors by name is safe either way, but a weights file whose
    #     first eight slots meant something else would be silently mis-scored.
    b = np.zeros((20, 10), dtype=np.int8)
    b[19][0] = b[19][1] = b[18][0] = 1          # some structure, not all zeros
    try:
        v10 = list(F.extract_named(sets["wells10"], b, 1.25, 2))
        v8 = list(F.extract_named(sets["dellacherie8"], b, 1.25, 2))
    except Exception as e:
        fail("W6", "extract_named raised on a known set: %s: %s"
             % (type(e).__name__, e))
        return
    if len(v10) == 10 and len(v8) == 8 and v10[:8] == v8:
        ok("wells10 EXTENDS dellacherie8: the first 8 components are identical, "
           "so the two new features are appended rather than interleaved and an "
           "8-feature weights file cannot be silently mis-indexed")
    else:
        fail("W6", "wells10 does not extend dellacherie8: len %d/%d, first-8 "
                   "equal=%s. A weights file's slots would then mean different "
                   "things depending on which set built the vector."
             % (len(v10), len(v8), v10[:8] == v8))

    # (b) an unknown name must be a HARD ERROR. Zero-filling is the `|| 0`
    #     failure mode: the panel just looks badly trained.
    try:
        got = list(F.extract_named(("holes", "no_such_feature_xyz"), b, 0.0, 0))
        fail("W6", "an UNKNOWN feature name was ACCEPTED and produced %r -- a "
                   "zero-filled slot makes a policy look weak rather than "
                   "broken, which is exactly how the landing_height bug hid. "
                   "It must raise." % got)
    except KeyError as e:
        msg = str(e)
        listed = "known" in msg.lower()
        ok("an unknown feature name raises KeyError%s -- no silent zero-fill, "
           "so a typo in a weights file's `features` list fails loudly instead "
           "of quietly degrading the policy"
           % (" and the message lists the known names" if listed else ""))
    except Exception as e:
        ok("an unknown feature name raises %s (not silently accepted)"
           % type(e).__name__)

    # (c) every policy file's declared feature list must be a known set, and
    #     its weight vector must be the same length
    print("\n7. do the shipped weights files agree with their declared sets?")
    import glob
    bad = 0
    checked = 0
    known = set(getattr(F, "KNOWN_FEATURES", []) or [])
    for path in sorted(glob.glob(os.path.join(_ROOT, "weights", "*.json"))):
        try:
            d = json.load(open(path, encoding="utf-8"))
        except Exception:
            continue
        if "kind" not in d or "features" not in d:
            continue
        checked += 1
        name = os.path.basename(path)
        feats = list(d["features"])
        unknown = [f for f in feats if known and f not in known]
        if unknown:
            bad += 1
            fail("W7", "%s declares unknown feature(s) %r -- the browser builds "
                       "vectors by name, so those slots cannot be filled"
                 % (name, unknown))
            continue
        w = d.get("weights")
        if isinstance(w, list) and len(w) != len(feats):
            bad += 1
            fail("W7", "%s declares %d features but carries %d weights -- the "
                       "vector and the weight vector cannot be dotted"
                 % (name, len(feats), len(w)))
    if checked and bad == 0:
        ok("%d weights files: every declared feature name is known and every "
           "linear weight vector matches its declared length" % checked)
    elif not checked:
        skip("W7", "no weights file declares a `features` list")


def report():
    print("\n" + "=" * 74)
    print("PASS %d   FAIL %d   SKIP %d" % (len(PASSED), len(FAILED),
                                           len(SKIPPED)))
    if SKIPPED:
        print("skipped (NOT verified, not passed):")
        for t, m in SKIPPED:
            print("  [%s] %s" % (t, m.splitlines()[0]))
    if FAILED:
        print("FINDINGS:")
        for t, m in FAILED:
            print("  [%s] %s" % (t, m))
        return 1
    if not PASSED:
        print("RESULT: NOTHING WAS VERIFIED -- %d skipped, 0 passed." % len(SKIPPED))
        return 1
    print("RESULT: my independent reading of the prose agrees with rl "
          "everywhere (%d checks)." % len(PASSED))
    return 0


if __name__ == "__main__":
    sys.exit(main())
